version: "3"
services:
  backend:
    container_name: backend 
    build: ./backend
    depends_on:
      - db  
    volumes:
      - ./backend:/usr/app
      - ./backend/package.json:/usr/app/package.json
      - ./backend/package-lock.json:/usr/app/package-lock.json
    environment:  
      - MONGO_URL=mongodb://db:27017/todos
      - APP_PORT=80
    command: npm start
    ports: ['80:80'] 
  db:
    container_name: db
    image: mongo:latest
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - './frontend:/app'
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
    ports:
      - '8080:8080'
    environment:  
      - BACKEND_URL=http://localhost/todos